export const products = [
  {
    id: "1",
    name: "iPhone Xr 128GB",
    image: "/images/iphoneXr.jpg",
    description:
      'iPhone XR 128GB - Blue Capacity: 128GB Display: - Liquid Retina HD display - 6.1-inch (diagonal) all-screen LCD Multi-Touch display with IPS technology - 792-by-828-pixel resolution at 326 ppi - 1400:1 contrast ratio (typical) - True Tone display - Wide colour display (P3) - 625 cd/m2 max brightness (typical) - Fingerprint-resistant oleo phobic coating - Support for display of multiple languages and characters simultaneously Splash, Water and dust Resistance',
    brand: "iPhone",
    category: "Device",
    price: 0,
    countInStock: 0,
    rating: 4.2,
    numReviews: 0,
  },
  {
    id: "2",
    name: "Samsung Galaxy A13",
    image: "/images/A13.jpg",
    description:
      "More display means more room to play Expand your view to the 6.6-inch Infinity-V Display of Galaxy A13 and see what you've been missing. And with FHD+ technology, your everyday content looks sharp, crisp and clear. Minimalist design with striking style Galaxy A13 combines soft colors with a look and feel that’s gentle to the touch. Refined curves make it comfortable to hold and provides easy screen navigation. Choose from Black, White, Blue, and Peach colors.",
    brand: "Samsung",
    category: "device",
    price: 4703.18,
    countInStock: 15,
    rating: 0,
    numReviews: 0,
  },
  {
    id: "3",
    name: "Project CARS 3",
    image: '/images/cars.jpg',
    description:
      "Project CARS 3 is the third instalment in the best-seller racing franchise that brings all the intense thrills, emotions and fun from the vibrant world of motor racing to vivid life as players undertake a whole new exciting career journey that sees them rise from weekend warrior to racing legend. Also new to the franchise is a deeply engaging metagame that challenges players to race hard and earn in-game Credits with which to buy and own hundreds of cars from the world’s most elite brands and race them all on dynamic and spectacular circuits around the globe featuring stunning all-weather, all-seasons conditions. ",
    brand: "Xbox",
    category: "game",
    price: 940.50,
    countInStock: 3,
    rating: 2.6,
    numReviews: 0,
  },
  {
    id: "4",
    name: "Macbook Pro sliverLining",
    image: '/images/macbook.jpg',
    description:
      "Project CARS 3 is the third instalment in the best-seller racing franchise that brings all the intense thrills, emotions and fun from the vibrant world of motor racing to vivid life as players undertake a whole new exciting career journey that sees them rise from weekend warrior to racing legend. Also new to the franchise is a deeply engaging metagame that challenges players to race hard and earn in-game Credits with which to buy and own hundreds of cars from the world’s most elite brands and race them all on dynamic and spectacular circuits around the globe featuring stunning all-weather, all-seasons conditions. ",
    brand: "Macintosh",
    category: "Devce",
    price: 37475.50,
    countInStock: 3,
    rating: 5,
    numReviews: 0,
  },
  {
    id: "5",
    name: "MECER computer Celeron",
    image: '/images/computer.webp',
    description:
      "Project CARS 3 is the third instalment in the best-seller racing franchise that brings all the intense thrills, emotions and fun from the vibrant world of motor racing to vivid life as players undertake a whole new exciting career journey that sees them rise from weekend warrior to racing legend. Also new to the franchise is a deeply engaging metagame that challenges players to race hard and earn in-game Credits with which to buy and own hundreds of cars from the world’s most elite brands and race them all on dynamic and spectacular circuits around the globe featuring stunning all-weather, all-seasons conditions. ",
    brand: "Xbox",
    category: "game",
    price: 940.50,
    countInStock: 3,
    rating: 5,
    numReviews: 0,
  },
  {
    id: "6",
    name: "Play Station 5",
    image: '/images/ps5.jpg',
    description:
      "Project CARS 3 is the third instalment in the best-seller racing franchise that brings all the intense thrills, emotions and fun from the vibrant world of motor racing to vivid life as players undertake a whole new exciting career journey that sees them rise from weekend warrior to racing legend. Also new to the franchise is a deeply engaging metagame that challenges players to race hard and earn in-game Credits with which to buy and own hundreds of cars from the world’s most elite brands and race them all on dynamic and spectacular circuits around the globe featuring stunning all-weather, all-seasons conditions. ",
    brand: "Xbox",
    category: "game",
    price: 940.50,
    countInStock: 3,
    rating: 4.5,
    numReviews: 0,
  },
];
